[tool.ruff]
line-length = 120
select = ["E", "F", "I", "UP"]
ignore = ["D203"]

[tool.ruff.isort]

[tool.black]
line-length = 120
exclude = '''
/(
  | migrations
)/
'''

[tool.pytest.ini_options]
addopts = "-ra --cov -vv"
DJANGO_SETTINGS_MODULE = "project.settings"

[tool.coverage.report]
show_missing = true
